### ISSUE TITLE
Bad state: Stream has already been listened to.

### ISSUE THREAD

**Issue by zianfahrudi** [qiscus/qiscus-multichannel-widget-flutter#7]
![alt tag](https://www.linkpicture.com/q/qiscus.png)
E/flutter ( 2950): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Stream has already been listened to.
E/flutter ( 2950): #0      _StreamController._subscribe (dart:async/stream_controller.dart:676:7)
E/flutter ( 2950): #1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:827:19)
E/flutter ( 2950): #2      _StreamImpl.listen (dart:async/stream_impl.dart:471:9)
E/flutter ( 2950): #3      new _AddStreamState (dart:async/stream_controller.dart:892:34)
E/flutter ( 2950): #4      new _StreamControllerAddStreamState (dart:async/stream_controller.dart:942:9)
E/flutter ( 2950): #5      _StreamController.addStream (dart:async/stream_controller.dart:576:9)
E/flutter ( 2950): #6      _AsyncStarStreamController.addStream (dart:async-patch/async_patch.dart:99:39)
E/flutter ( 2950): #7      QiscusSDK.onMessageRead (package:qiscus_chat_sdk/src/qiscus.dart)
qiscus.dart:1
E/flutter ( 2950): <asynchronous suspension>
E/flutter ( 2950):
E/flutter ( 2950): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Stream has already been listened to.
E/flutter ( 2950): #0      _StreamController._subscribe (dart:async/stream_controller.dart:676:7)
E/flutter ( 2950): #1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:827:19)
E/flutter ( 2950): #2      _StreamImpl.listen (dart:async/stream_impl.dart:471:9)
E/flutter ( 2950): #3      new _AddStreamState (dart:async/stream_controller.dart:892:34)
E/flutter ( 2950): #4      new _StreamControllerAddStreamState (dart:async/stream_controller.dart:942:9)
E/flutter ( 2950): #5      _StreamController.addStream (dart:async/stream_controller.dart:576:9)
E/flutter ( 2950): #6      _AsyncStarStreamController.addStream (dart:async-patch/async_patch.dart:99:39)
E/flutter ( 2950): #7      QiscusSDK.onMessageDelivered (package:qiscus_chat_sdk/src/qiscus.dart)
qiscus.dart:1
E/flutter ( 2950): <asynchronous suspension>
E/flutter ( 2950):
2
I/flutter ( 2950): on do back!
I/flutter ( 2950): initiate chat!
[log] set user! Fita
E/flutter ( 2950): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: Stream has already been listened to.
E/flutter ( 2950): #0      _StreamController._subscribe (dart:async/stream_controller.dart:676:7)
E/flutter ( 2950): #1      _ControllerStream._createSubscription (dart:async/stream_controller.dart:827:19)
E/flutter ( 2950): #2      _StreamImpl.listen (dart:async/stream_impl.dart:471:9)
E/flutter ( 2950): #3      new _AddStreamState (dart:async/stream_controller.dart:892:34)
E/flutter ( 2950): #4      new _StreamControllerAddStreamState (dart:async/stream_controller.dart:942:9)
E/flutter ( 2950): #5      _StreamController.addStream (dart:async/stream_controller.dart:576:9)
E/flutter ( 2950): #6      _AsyncStarStreamController.addStream (dart:async-patch/async_patch.dart:99:39)
E/flutter ( 2950): #7      QiscusSDK.onMessageRead (package:qiscus_chat_sdk/src/qiscus.dart)
qiscus.dart:1
E/flutter ( 2950): <asynchronous suspension>
E/flutter ( 2950):

**Comment by zianfahrudi** [comment]
Kasus nya ketika login -> chatroomscreen -> onback -> login -> chatroomscreen.
Pesan terakhir terkirim tapi tidak ter-load jika onback dan login kembali.
Thanks, qiscus team.
